### ISSUE TITLE
Could not build your Dockerfile - Syntax error

### ISSUE THREAD

**Issue by suelm** [mumez/pharo-vnc-supervisor#7]
When I try to use your Dockerfile and rebuild it I get this error:

Step 16/36 : RUN mkdir pharo && cd pharo   && apt-get update && apt-get install -y --no-install-recommends     curl     unzip   && curl https://get.pharo.org/64/${PHARO_IMAGE_VERSION}+vm | bash   && mv ../pharo /usr/local/bin/   && apt-get remove -y     unzip   && rm -rf /var/lib/apt/lists/*
 ---> Running in e2355f601c3c
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [81.2 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [652 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9,802 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.7 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [450 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3,735 B]
Get:11 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1,558 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9,827 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [257 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1,028 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.1 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [821 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.8 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [5,157 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [8,080 B]
Fetched 25.3 MB in 5s (4,571 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  dbus-x11 dictionaries-common emacsen-common gconf-service
  gconf-service-backend gconf2 gconf2-common libart-2.0-2 libavahi-glib1
  libbonobo2-0 libbonobo2-common libbonoboui2-0 libbonoboui2-common
  libcanberra0 libgail18 libgconf-2-4 libglade2-0 libgnome-2-0
  libgnome-keyring-common libgnome-keyring0 libgnome2-0 libgnome2-bin
  libgnome2-common libgnomecanvas2-0 libgnomecanvas2-common libgnomeui-0
  libgnomeui-common libgnomevfs2-0 libgnomevfs2-common libgtk2.0-0
  libgtk2.0-bin libgtk2.0-common libjpeg-progs libjpeg9 liborbit-2-0 libtdb1
  libvorbis0a libvorbisfile3 miscfiles sound-theme-freedesktop
Use 'apt autoremove' to remove them.
Suggested packages:
  zip
The following NEW packages will be installed:
  curl unzip
0 upgraded, 2 newly installed, 0 to remove and 58 not upgraded.
Need to get 297 kB of archives.
After this operation, 869 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 curl amd64 7.47.0-1ubuntu2.8 [139 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 unzip amd64 6.0-20ubuntu1 [158 kB]
Fetched 297 kB in 0s (1,265 kB/s)
Selecting previously unselected package curl.
(Reading database ... 47517 files and directories currently installed.)
Preparing to unpack .../curl_7.47.0-1ubuntu2.8_amd64.deb ...
Unpacking curl (7.47.0-1ubuntu2.8) ...
Selecting previously unselected package unzip.
Preparing to unpack .../unzip_6.0-20ubuntu1_amd64.deb ...
Unpacking unzip (6.0-20ubuntu1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up curl (7.47.0-1ubuntu2.8) ...
Setting up unzip (6.0-20ubuntu1) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   204  100   204    0     0    483      0 --:--:-- --:--:-- --:--:--   482
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">'
The command '/bin/sh -c mkdir pharo && cd pharo   && apt-get update && apt-get install -y --no-install-recommends     curl     unzip   && curl https://get.pharo.org/64/${PHARO_IMAGE_VERSION}+vm | bash   && mv ../pharo /usr/local/bin/   && apt-get remove -y     unzip   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2

When I replace https://get.pharo.org/64/${PHARO_IMAGE_VERSION}+vm with https://get.pharo.org/64/61+vm the build ist successful. 
But after build and start VNC pharo is not coming up. Any ideas?

**Comment by mumez** [comment]
It is a bit strange because I set the ARG `PHARO_IMAGE_VERSION` here:
https://github.com/mumez/pharo-vnc-supervisor/blob/master/Dockerfile#L19
But your docker environment ignores `${PHARO_IMAGE_VERSION}` in RUN command.

Did you try `--build-arg` for overriding `PHARO_IMAGE_VERSION` ?
If you do not use the option, PHARO_IMAGE_VERSION will be set to `61` (default in Dockerfile) and pharo 6.1 will be downloaded.

I've attached the build log of `docker build -t pharo70-vnc-supervisor .`.
[successful_build_log.txt](https://github.com/mumez/pharo-vnc-supervisor/files/2147381/successful_build_log.txt)

I'm using Docker 18.03.1 on Mac.
`ume@umezawa-no-MacBook-Pro:~/Desktop/pharo-vnc-supervisor-master$ docker -v
Docker version 18.03.1-ce, build 9ee9f40`

**Comment by suelm** [comment]
I build with `docker build -t name .` and run without any parameter.
In the docker file I ignore the ARG `PHARO_IMAGE_VERSION` and use ` && curl https://get.pharo.org/61+vmT | bash \` -> I need this version. With this, the build is successful but after container start, Pharo does not start.

**Comment by mumez** [comment]
The value ARG `PHARO_DEFAULT_IMAGE_DIR` is used for the default value of ENG `PHARO_HOME`.
https://github.com/mumez/pharo-vnc-supervisor/blob/master/Dockerfile#L24

If your docker environment does not interpret ARG on build time, `PHARO_HOME` will be undefined in run-time. So `setup.sh` and `launch-pharo.sh` will be failed.

I think the workaround is to set `ENV PHARO_HOME='/root/data'` in Dockerfile. But I can not figure out why ARGs are not properly set in your docker environment.  Do you use an older docker that does not supprt ARG?

**Comment by suelm** [comment]
It seems that there is a special problem with ENV and ARG with my Docker installation on Synology. So I close here.
